export const skCytoscapeStyles: any[] = [
  {
    selector: 'node',
    style: {
      'label': 'data(label)',
      'text-valign': 'center',
      'text-halign': 'center',
      'font-size': 10,
      'font-weight': 600,
      'font-family': 'Inter, system-ui, sans-serif',
      'color': '#e7e5e4',
      'text-background-color': '#1c1917',
      'text-background-opacity': 0.7,
      'text-background-padding': '2px',
      'background-color': 'data(bgColor)',
      'border-color': 'data(borderColor)',
      'border-width': 2,
      'shape': 'data(shape)',
      'width': 35,
      'height': 35,
    } as any,
  },
  {
    selector: 'node[significance="major"]',
    style: { 'width': 50, 'height': 50, 'font-size': 12 } as any,
  },
  {
    selector: 'node[significance="notable"]',
    style: { 'width': 40, 'height': 40, 'font-size': 11 } as any,
  },
  {
    selector: 'edge',
    style: {
      'width': 1.5,
      'line-color': '#57534e',
      'target-arrow-color': '#57534e',
      'target-arrow-shape': 'triangle',
      'arrow-scale': 0.8,
      'curve-style': 'bezier',
      'opacity': 0.6,
    } as any,
  },
  // Relationship type styles
  { selector: 'edge[relType="ally"]', style: { 'line-color': '#22c55e', 'target-arrow-color': '#22c55e', 'width': 2 } as any },
  { selector: 'edge[relType="enemy"]', style: { 'line-color': '#ef4444', 'target-arrow-color': '#ef4444', 'line-style': 'dashed', 'width': 2 } as any },
  { selector: 'edge[relType="marriage"]', style: { 'line-color': '#f472b6', 'target-arrow-color': '#f472b6', 'target-arrow-shape': 'none' } as any },
  { selector: 'edge[relType="parent-child"]', style: { 'line-color': '#78716c', 'target-arrow-color': '#78716c' } as any },
  { selector: 'edge[relType="succession"]', style: { 'line-color': '#3b82f6', 'target-arrow-color': '#3b82f6', 'width': 2 } as any },
  { selector: 'edge[relType="prophet-to-king"]', style: { 'line-color': '#a78bfa', 'target-arrow-color': '#a78bfa', 'line-style': 'dotted', 'width': 2 } as any },
  { selector: 'edge[relType="betrayal"]', style: { 'line-color': '#f97316', 'target-arrow-color': '#f97316', 'line-style': 'dashed' } as any },
  { selector: 'edge[relType="murder"]', style: { 'line-color': '#b91c1c', 'target-arrow-color': '#b91c1c', 'width': 3, 'line-style': 'dotted' } as any },
  { selector: 'edge[relType="counsel"]', style: { 'line-color': '#60a5fa', 'target-arrow-color': '#60a5fa', 'line-style': 'dotted' } as any },
  { selector: 'edge[relType="judgment"]', style: { 'line-color': '#7c3aed', 'target-arrow-color': '#7c3aed', 'width': 2.5 } as any },
  { selector: 'edge[relType="anointing"]', style: { 'line-color': '#eab308', 'target-arrow-color': '#eab308', 'width': 2.5 } as any },
  { selector: 'edge[relType="rebellion"]', style: { 'line-color': '#f97316', 'target-arrow-color': '#f97316', 'line-style': 'dashed', 'width': 2.5 } as any },
  { selector: 'edge[relType="treaty"]', style: { 'line-color': '#22d3ee', 'target-arrow-color': '#22d3ee', 'line-style': 'dashed' } as any },
  // States
  { selector: 'node:selected', style: { 'border-width': 4, 'border-color': '#ffffff', 'overlay-opacity': 0.15, 'overlay-color': '#ffffff' } as any },
  { selector: '.highlighted', style: { 'border-width': 3, 'border-color': '#60a5fa', 'z-index': 999 } as any },
  { selector: '.dimmed', style: { 'opacity': 0.15 } as any },
  { selector: '.hidden', style: { 'display': 'none' } as any },
];
